### ISSUE TITLE
PlayerMap and Opponent Map properties null

### ISSUE THREAD

**Issue by leonardseymore** [EntelectChallenge/2017-Battleships#15]
Hi,

I just started looking at the code and noticed that the PlayerMap and Opponent Map properties are null on the GameState. The JSON generated by the Game Engine has Player1Map and Player2Map properties that do have data. Is this the expected result? I assume not, because of how the reference bot class looks:

Game State class
```
public class GameState {

    public PlayerMap PlayerMap;

    public OpponentMap OpponentMap;

    public String GameVersion;

    public int GameLevel;

    public int Round;

    public int MapDimension;

    public int Phase;
}
```

Game Engine JSON
```
{
  "PlayerMap": null,
  "OpponentMap": null,
  "GameVersion": "1.0.0",
  "GameLevel": 1,
  "Round": 50,
  "MapDimension": 10,
  "Phase": 2,
  "Player1Map": {...valid data...}
  "Player2Map": {...valid data...}
}
```

**Comment by jan1za** [comment]
The application does work, check your json file in the root of your bot, make sure it is pointing to your exe.

**Comment by EntelectChallenge** [comment]
Hi there, this is seems to be a bug as they should contain information, we will have a look at this.

**Comment by EntelectChallenge** [comment]
Hi Leonard,

The game engine produces two different types of state files.  The one generated for the bots will have values for the PlayerMap and OpponentMap properties.  After the bots have made their move the game engine will write a more general state file that will be used by the game visualizer that contains the full version of both player's state file, which is the one you are looking at.
