### ISSUE TITLE
Feature: forceRebuild to allow Game Engine to rebuild bots before run

### ISSUE THREAD

**Issue by svanellewee** [EntelectChallenge/2017-Battleships#26]
I've created a PR https://github.com/EntelectChallenge/2017-Battleships/pull/25 that implements rebuilding of DotNet and Golang bots before each match.

Example usage:
```bash
mono Battleships.exe -b $(SAMPLEBOTHOME)/Java/SampleBot  $(SAMPLEBOTHOME)/Golang  --clog --pretty --debug --forceRebuild
```

**Comment by EntelectChallenge** [comment]
Hi Svanellewee,

Thanks, we will have a look at that.  Usually for the tournament we will build the bot only once, right after you uploaded it to the portal and before the test match is played.  That version is then used for the rest of the tournament.

But I can see how this would be useful so thank you for the contribution.

**Comment by svanellewee** [comment]
Sure thing. I really need to test the compilation step for my specific language implementation (Go), so having the BotCompiler code accessible and testable is something I need, either via this optional switch or through some other means. I'll really appreciate any method you can suggest that make testing the compilation step easier.
