### ISSUE TITLE
Environment variable setting for game engine building

### ISSUE THREAD

**Issue by svanellewee** [EntelectChallenge/2017-Battleships#36]
I need some way to set environment variables before building my code (Go requires this for any large complex codebase.) 

I've suggested some changes here : https://github.com/EntelectChallenge/2017-Battleships/pull/33 but if there is a better way of doing this I'm open to those suggestions as well.
Best regards,
Stephan

**Comment by EntelectChallenge** [comment]
Hi Stephan,

We reviewed the pull request.  I am happy with the changes you made and merged it in.  If there are any additional environment variables we might need in the future we can look at an alternative way of doing it.
