### ISSUE TITLE
ShipsRemaing-> ShipsRemaining in Scala sample

### ISSUE THREAD

**Issue by gkmauer** [EntelectChallenge/2017-Battleships#41]
Hi

I notice you have fixed the spelling of ShipsRemaing to ShipsRemaining in the state.json.

Can you maybe please also fix in on this line when you have a moment:
https://github.com/EntelectChallenge/2017-Battleships/blob/master/Sample%20Bots/Scala/SampleBot/src/main/scala/za/co/sample/GameMapParser.scala#L36

If you do not mind, I would prefer not to go through the whole process to generate a pull request for two characters.

**Comment by EntelectChallenge** [comment]
Hi gkmauer,

I updated the files.
