### ISSUE TITLE
Broken reference bot

### ISSUE THREAD

**Issue by jonathan-alvaro** [EntelectChallenge/2017-Battleships#55]
When I ran the RunGame.bat for some reason the program gives an index error.

**Comment by Edwin-Entelect** [comment]
Hi oathofoblivion,

Can you maybe provide a bit more detail on your error?

The first thing that comes to mind is that maybe the bot you are playing is trying to either place or shoot outside of the map.

**Comment by yonasadiel** [comment]
trying to help - on [current released file (1.2.2)](https://github.com/EntelectChallenge/2017-Battleships/releases/tag/1.2.2), bot.json have RunFile `bin\\Debug\\ReferenceBot.exe` while it should be `ReferenceBot.exe`

**Comment by jonathan-alvaro** [comment]
I just found out the problem. It turns out that the default ship placement given in the python3 bot script is invalid. I think it either places some ships out of the map or over each other. Perhaps you could change it to prevent confusion from future users.
