### ISSUE TITLE
Mixed up files, Instructions don't match

### ISSUE THREAD

**Issue by GlenBoonzaier** [EntelectChallenge/2017-Battleships#6]
The 2017-Battleships-1.0.0 has the files a bit muddled up.

There is a 2017-Battleships-1.0.0\GameEngine\GameEngine.csproj
which seems to be the same as 2017-Battleships-1.0.0\GameEngine\Battleships\GameEngine\GameEngine.csproj

The 2017-Battleships-1.0.0\GameEngine\Battleships\Battleships.sln solution seems to be the main program but is in a subdirectory of the GameEngine Project?

There is also no run.bat that allows you to watch the demo bots go at it.

**Comment by raezor07** [comment]
Hi Glen, I have requested a Pull Request for the duplicate files.
Refer to pull request **#4** for more info.

As for a run.bat file, I could send you one I created if you want?

**Comment by GlenBoonzaier** [comment]
Thanks @raezor07 that would be much appreciated.  Could you send it to glenboonzaier at gmail please?

The instructions as per your Usage section has the following line:

> We have included the reference bot in the binaries version folder, so at this point you can simply run the Run.bat to see the bots play a match.

Which is why I mentioned it.

**Comment by EntelectChallenge** [comment]
Hi GlenBoonzaier,

The RunGame.bat file is inside of the game engine release zip file under the releases section.  I don't believe it is part for the source files in the repo.
